package pojos;
// Generated 29-Nov-2018 04:16:50 by Hibernate Tools 4.3.1



/**
 * Kantor generated by hbm2java
 */
public class Kantor  implements java.io.Serializable {


     private String idKantor;
     private String jenis;
     private String posisi;

    public Kantor() {
    }

    public Kantor(String idKantor, String jenis, String posisi) {
       this.idKantor = idKantor;
       this.jenis = jenis;
       this.posisi = posisi;
    }
   
    public String getIdKantor() {
        return this.idKantor;
    }
    
    public void setIdKantor(String idKantor) {
        this.idKantor = idKantor;
    }
    public String getJenis() {
        return this.jenis;
    }
    
    public void setJenis(String jenis) {
        this.jenis = jenis;
    }
    public String getPosisi() {
        return this.posisi;
    }
    
    public void setPosisi(String posisi) {
        this.posisi = posisi;
    }




}


