package pojos;
// Generated 29-Nov-2018 04:16:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Kurir generated by hbm2java
 */
public class Kurir  implements java.io.Serializable {


     private int nik;
     private String nama;
     private String alamat;
     private String status;
     private String noTelp;
     private String agama;
     private Date tanggalLahir;

    public Kurir() {
    }

	
    public Kurir(int nik) {
        this.nik = nik;
    }
    public Kurir(int nik, String nama, String alamat, String status, String noTelp, String agama, Date tanggalLahir) {
       this.nik = nik;
       this.nama = nama;
       this.alamat = alamat;
       this.status = status;
       this.noTelp = noTelp;
       this.agama = agama;
       this.tanggalLahir = tanggalLahir;
    }
   
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getAgama() {
        return this.agama;
    }
    
    public void setAgama(String agama) {
        this.agama = agama;
    }
    public Date getTanggalLahir() {
        return this.tanggalLahir;
    }
    
    public void setTanggalLahir(Date tanggalLahir) {
        this.tanggalLahir = tanggalLahir;
    }




}


