package pojos;
// Generated 29-Nov-2018 03:14:22 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Perjalanan generated by hbm2java
 */
public class Perjalanan  implements java.io.Serializable {


     private Integer idPerjalanan;
     private int idBarang;
     private String asal;
     private String tujuan;
     private String waktuDiterima;
     private Date tanggalDiterima;
     private String namaPenerima;

    public Perjalanan() {
    }

	
    public Perjalanan(int idBarang, String asal, String tujuan, String waktuDiterima, Date tanggalDiterima) {
        this.idBarang = idBarang;
        this.asal = asal;
        this.tujuan = tujuan;
        this.waktuDiterima = waktuDiterima;
        this.tanggalDiterima = tanggalDiterima;
    }
    public Perjalanan(int idBarang, String asal, String tujuan, String waktuDiterima, Date tanggalDiterima, String namaPenerima) {
       this.idBarang = idBarang;
       this.asal = asal;
       this.tujuan = tujuan;
       this.waktuDiterima = waktuDiterima;
       this.tanggalDiterima = tanggalDiterima;
       this.namaPenerima = namaPenerima;
    }
   
    public Integer getIdPerjalanan() {
        return this.idPerjalanan;
    }
    
    public void setIdPerjalanan(Integer idPerjalanan) {
        this.idPerjalanan = idPerjalanan;
    }
    public int getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(int idBarang) {
        this.idBarang = idBarang;
    }
    public String getAsal() {
        return this.asal;
    }
    
    public void setAsal(String asal) {
        this.asal = asal;
    }
    public String getTujuan() {
        return this.tujuan;
    }
    
    public void setTujuan(String tujuan) {
        this.tujuan = tujuan;
    }
    public String getWaktuDiterima() {
        return this.waktuDiterima;
    }
    
    public void setWaktuDiterima(String waktuDiterima) {
        this.waktuDiterima = waktuDiterima;
    }
    public Date getTanggalDiterima() {
        return this.tanggalDiterima;
    }
    
    public void setTanggalDiterima(Date tanggalDiterima) {
        this.tanggalDiterima = tanggalDiterima;
    }
    public String getNamaPenerima() {
        return this.namaPenerima;
    }
    
    public void setNamaPenerima(String namaPenerima) {
        this.namaPenerima = namaPenerima;
    }




}


