package pojos;
// Generated 28-Nov-2018 10:40:36 by Hibernate Tools 4.3.1



/**
 * Perjalanan generated by hbm2java
 */
public class Perjalanan  implements java.io.Serializable {


     private Integer idPerjalanan;
     private int idBarang;
     private String asal;
     private String tujuan;

    public Perjalanan() {
    }

    public Perjalanan(int idBarang, String asal, String tujuan) {
       this.idBarang = idBarang;
       this.asal = asal;
       this.tujuan = tujuan;
    }
   
    public Integer getIdPerjalanan() {
        return this.idPerjalanan;
    }
    
    public void setIdPerjalanan(Integer idPerjalanan) {
        this.idPerjalanan = idPerjalanan;
    }
    public int getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(int idBarang) {
        this.idBarang = idBarang;
    }
    public String getAsal() {
        return this.asal;
    }
    
    public void setAsal(String asal) {
        this.asal = asal;
    }
    public String getTujuan() {
        return this.tujuan;
    }
    
    public void setTujuan(String tujuan) {
        this.tujuan = tujuan;
    }




}


