package pojos;
// Generated 14-Nov-2018 13:53:41 by Hibernate Tools 4.3.1



/**
 * TabelStokBarangToko generated by hbm2java
 */
public class TabelStokBarangToko  implements java.io.Serializable {


     private Integer idbarangToko;
     private String namaBarang;
     private int jumlahBarang;
     private int hargaBarang;

    public TabelStokBarangToko() {
    }

    public TabelStokBarangToko(String namaBarang, int jumlahBarang, int hargaBarang) {
       this.namaBarang = namaBarang;
       this.jumlahBarang = jumlahBarang;
       this.hargaBarang = hargaBarang;
    }
   
    public Integer getIdbarangToko() {
        return this.idbarangToko;
    }
    
    public void setIdbarangToko(Integer idbarangToko) {
        this.idbarangToko = idbarangToko;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public int getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(int jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }
    public int getHargaBarang() {
        return this.hargaBarang;
    }
    
    public void setHargaBarang(int hargaBarang) {
        this.hargaBarang = hargaBarang;
    }




}


