package pojos;
// Generated 14-Nov-2018 13:53:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TabelKirimBarang generated by hbm2java
 */
public class TabelKirimBarang  implements java.io.Serializable {


     private Integer idbarang;
     private String namaBarang;
     private int jumlahBarang;
     private Date tanggal;

    public TabelKirimBarang() {
    }

    public TabelKirimBarang(String namaBarang, int jumlahBarang, Date tanggal) {
       this.namaBarang = namaBarang;
       this.jumlahBarang = jumlahBarang;
       this.tanggal = tanggal;
    }
   
    public Integer getIdbarang() {
        return this.idbarang;
    }
    
    public void setIdbarang(Integer idbarang) {
        this.idbarang = idbarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public int getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(int jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }




}


