package pojos;
// Generated 14-Nov-2018 13:53:41 by Hibernate Tools 4.3.1



/**
 * TabelToko generated by hbm2java
 */
public class TabelToko  implements java.io.Serializable {


     private Integer idtoko;
     private String namaToko;
     private String alamatToko;

    public TabelToko() {
    }

    public TabelToko(String namaToko, String alamatToko) {
       this.namaToko = namaToko;
       this.alamatToko = alamatToko;
    }
   
    public Integer getIdtoko() {
        return this.idtoko;
    }
    
    public void setIdtoko(Integer idtoko) {
        this.idtoko = idtoko;
    }
    public String getNamaToko() {
        return this.namaToko;
    }
    
    public void setNamaToko(String namaToko) {
        this.namaToko = namaToko;
    }
    public String getAlamatToko() {
        return this.alamatToko;
    }
    
    public void setAlamatToko(String alamatToko) {
        this.alamatToko = alamatToko;
    }




}


