package pojos;
// Generated 14-Nov-2018 13:53:41 by Hibernate Tools 4.3.1



/**
 * TabelStokGudang generated by hbm2java
 */
public class TabelStokGudang  implements java.io.Serializable {


     private Integer idbarangGudang;
     private String namaBarang;
     private int jumlahBarang;

    public TabelStokGudang() {
    }

    public TabelStokGudang(String namaBarang, int jumlahBarang) {
       this.namaBarang = namaBarang;
       this.jumlahBarang = jumlahBarang;
    }
   
    public Integer getIdbarangGudang() {
        return this.idbarangGudang;
    }
    
    public void setIdbarangGudang(Integer idbarangGudang) {
        this.idbarangGudang = idbarangGudang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public int getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(int jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }




}


