package pojos;
// Generated 06-Nov-2018 10:28:42 by Hibernate Tools 4.3.1



/**
 * TabelStokGudang generated by hbm2java
 */
public class TabelStokGudang  implements java.io.Serializable {


     private Integer idbarang;
     private String namaBarang;
     private Integer jumlahBarang;

    public TabelStokGudang() {
    }

    public TabelStokGudang(String namaBarang, Integer jumlahBarang) {
       this.namaBarang = namaBarang;
       this.jumlahBarang = jumlahBarang;
    }
   
    public Integer getIdbarang() {
        return this.idbarang;
    }
    
    public void setIdbarang(Integer idbarang) {
        this.idbarang = idbarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public Integer getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(Integer jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }




}


