package pojos;
// Generated 06-Nov-2018 16:34:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TabelToko generated by hbm2java
 */
public class TabelToko  implements java.io.Serializable {


     private Integer idtoko;
     private String namaToko;
     private String alamatToko;
     private Set tabelTransaksis = new HashSet(0);
     private Set tabelStokBarangTokos = new HashSet(0);
     private Set tabelKirimBarangs = new HashSet(0);

    public TabelToko() {
    }

	
    public TabelToko(String namaToko, String alamatToko) {
        this.namaToko = namaToko;
        this.alamatToko = alamatToko;
    }
    public TabelToko(String namaToko, String alamatToko, Set tabelTransaksis, Set tabelStokBarangTokos, Set tabelKirimBarangs) {
       this.namaToko = namaToko;
       this.alamatToko = alamatToko;
       this.tabelTransaksis = tabelTransaksis;
       this.tabelStokBarangTokos = tabelStokBarangTokos;
       this.tabelKirimBarangs = tabelKirimBarangs;
    }
   
    public Integer getIdtoko() {
        return this.idtoko;
    }
    
    public void setIdtoko(Integer idtoko) {
        this.idtoko = idtoko;
    }
    public String getNamaToko() {
        return this.namaToko;
    }
    
    public void setNamaToko(String namaToko) {
        this.namaToko = namaToko;
    }
    public String getAlamatToko() {
        return this.alamatToko;
    }
    
    public void setAlamatToko(String alamatToko) {
        this.alamatToko = alamatToko;
    }
    public Set getTabelTransaksis() {
        return this.tabelTransaksis;
    }
    
    public void setTabelTransaksis(Set tabelTransaksis) {
        this.tabelTransaksis = tabelTransaksis;
    }
    public Set getTabelStokBarangTokos() {
        return this.tabelStokBarangTokos;
    }
    
    public void setTabelStokBarangTokos(Set tabelStokBarangTokos) {
        this.tabelStokBarangTokos = tabelStokBarangTokos;
    }
    public Set getTabelKirimBarangs() {
        return this.tabelKirimBarangs;
    }
    
    public void setTabelKirimBarangs(Set tabelKirimBarangs) {
        this.tabelKirimBarangs = tabelKirimBarangs;
    }




}


