package pojos;
// Generated 06-Nov-2018 16:34:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TabelGudang generated by hbm2java
 */
public class TabelGudang  implements java.io.Serializable {


     private Integer idgudang;
     private String namaGudang;
     private String alamatGudang;
     private Set tabelStokGudangs = new HashSet(0);

    public TabelGudang() {
    }

	
    public TabelGudang(String namaGudang, String alamatGudang) {
        this.namaGudang = namaGudang;
        this.alamatGudang = alamatGudang;
    }
    public TabelGudang(String namaGudang, String alamatGudang, Set tabelStokGudangs) {
       this.namaGudang = namaGudang;
       this.alamatGudang = alamatGudang;
       this.tabelStokGudangs = tabelStokGudangs;
    }
   
    public Integer getIdgudang() {
        return this.idgudang;
    }
    
    public void setIdgudang(Integer idgudang) {
        this.idgudang = idgudang;
    }
    public String getNamaGudang() {
        return this.namaGudang;
    }
    
    public void setNamaGudang(String namaGudang) {
        this.namaGudang = namaGudang;
    }
    public String getAlamatGudang() {
        return this.alamatGudang;
    }
    
    public void setAlamatGudang(String alamatGudang) {
        this.alamatGudang = alamatGudang;
    }
    public Set getTabelStokGudangs() {
        return this.tabelStokGudangs;
    }
    
    public void setTabelStokGudangs(Set tabelStokGudangs) {
        this.tabelStokGudangs = tabelStokGudangs;
    }




}


