package pojos;
// Generated 06-Nov-2018 10:28:42 by Hibernate Tools 4.3.1



/**
 * TabelStokBarangToko generated by hbm2java
 */
public class TabelStokBarangToko  implements java.io.Serializable {


     private Integer idbarang;
     private String namaBarang;
     private Integer jumlahBarang;
     private Integer hargaBarang;

    public TabelStokBarangToko() {
    }

    public TabelStokBarangToko(String namaBarang, Integer jumlahBarang, Integer hargaBarang) {
       this.namaBarang = namaBarang;
       this.jumlahBarang = jumlahBarang;
       this.hargaBarang = hargaBarang;
    }
   
    public Integer getIdbarang() {
        return this.idbarang;
    }
    
    public void setIdbarang(Integer idbarang) {
        this.idbarang = idbarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public Integer getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(Integer jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }
    public Integer getHargaBarang() {
        return this.hargaBarang;
    }
    
    public void setHargaBarang(Integer hargaBarang) {
        this.hargaBarang = hargaBarang;
    }




}


