package pojos;
// Generated 06-Nov-2018 16:34:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TabelStokBarangToko generated by hbm2java
 */
public class TabelStokBarangToko  implements java.io.Serializable {


     private Integer idbarangToko;
     private TabelKirimBarang tabelKirimBarang;
     private TabelToko tabelToko;
     private String namaBarang;
     private int jumlahBarang;
     private int hargaBarang;
     private Set tabelTransaksis = new HashSet(0);

    public TabelStokBarangToko() {
    }

	
    public TabelStokBarangToko(String namaBarang, int jumlahBarang, int hargaBarang) {
        this.namaBarang = namaBarang;
        this.jumlahBarang = jumlahBarang;
        this.hargaBarang = hargaBarang;
    }
    public TabelStokBarangToko(TabelKirimBarang tabelKirimBarang, TabelToko tabelToko, String namaBarang, int jumlahBarang, int hargaBarang, Set tabelTransaksis) {
       this.tabelKirimBarang = tabelKirimBarang;
       this.tabelToko = tabelToko;
       this.namaBarang = namaBarang;
       this.jumlahBarang = jumlahBarang;
       this.hargaBarang = hargaBarang;
       this.tabelTransaksis = tabelTransaksis;
    }
   
    public Integer getIdbarangToko() {
        return this.idbarangToko;
    }
    
    public void setIdbarangToko(Integer idbarangToko) {
        this.idbarangToko = idbarangToko;
    }
    public TabelKirimBarang getTabelKirimBarang() {
        return this.tabelKirimBarang;
    }
    
    public void setTabelKirimBarang(TabelKirimBarang tabelKirimBarang) {
        this.tabelKirimBarang = tabelKirimBarang;
    }
    public TabelToko getTabelToko() {
        return this.tabelToko;
    }
    
    public void setTabelToko(TabelToko tabelToko) {
        this.tabelToko = tabelToko;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public int getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(int jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }
    public int getHargaBarang() {
        return this.hargaBarang;
    }
    
    public void setHargaBarang(int hargaBarang) {
        this.hargaBarang = hargaBarang;
    }
    public Set getTabelTransaksis() {
        return this.tabelTransaksis;
    }
    
    public void setTabelTransaksis(Set tabelTransaksis) {
        this.tabelTransaksis = tabelTransaksis;
    }




}


