package pojos;
// Generated 06-Nov-2018 16:34:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TabelStokGudang generated by hbm2java
 */
public class TabelStokGudang  implements java.io.Serializable {


     private Integer idbarangGudang;
     private TabelGudang tabelGudang;
     private String namaBarang;
     private int jumlahBarang;
     private Set tabelKirimBarangs = new HashSet(0);

    public TabelStokGudang() {
    }

	
    public TabelStokGudang(String namaBarang, int jumlahBarang) {
        this.namaBarang = namaBarang;
        this.jumlahBarang = jumlahBarang;
    }
    public TabelStokGudang(TabelGudang tabelGudang, String namaBarang, int jumlahBarang, Set tabelKirimBarangs) {
       this.tabelGudang = tabelGudang;
       this.namaBarang = namaBarang;
       this.jumlahBarang = jumlahBarang;
       this.tabelKirimBarangs = tabelKirimBarangs;
    }
   
    public Integer getIdbarangGudang() {
        return this.idbarangGudang;
    }
    
    public void setIdbarangGudang(Integer idbarangGudang) {
        this.idbarangGudang = idbarangGudang;
    }
    public TabelGudang getTabelGudang() {
        return this.tabelGudang;
    }
    
    public void setTabelGudang(TabelGudang tabelGudang) {
        this.tabelGudang = tabelGudang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public int getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(int jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }
    public Set getTabelKirimBarangs() {
        return this.tabelKirimBarangs;
    }
    
    public void setTabelKirimBarangs(Set tabelKirimBarangs) {
        this.tabelKirimBarangs = tabelKirimBarangs;
    }




}


