package pojos;
// Generated 06-Nov-2018 10:28:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TabelTransaksi generated by hbm2java
 */
public class TabelTransaksi  implements java.io.Serializable {


     private Integer idbarang;
     private String namaBarang;
     private Integer hargaBarang;
     private Integer jumlahBarang;
     private Integer hargaTotal;
     private Date tanggal;

    public TabelTransaksi() {
    }

    public TabelTransaksi(String namaBarang, Integer hargaBarang, Integer jumlahBarang, Integer hargaTotal, Date tanggal) {
       this.namaBarang = namaBarang;
       this.hargaBarang = hargaBarang;
       this.jumlahBarang = jumlahBarang;
       this.hargaTotal = hargaTotal;
       this.tanggal = tanggal;
    }
   
    public Integer getIdbarang() {
        return this.idbarang;
    }
    
    public void setIdbarang(Integer idbarang) {
        this.idbarang = idbarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public Integer getHargaBarang() {
        return this.hargaBarang;
    }
    
    public void setHargaBarang(Integer hargaBarang) {
        this.hargaBarang = hargaBarang;
    }
    public Integer getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(Integer jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }
    public Integer getHargaTotal() {
        return this.hargaTotal;
    }
    
    public void setHargaTotal(Integer hargaTotal) {
        this.hargaTotal = hargaTotal;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }




}


